function getDom() {
  return {
    sideload: document.getElementById("sideload-msg"),
    appBody: document.getElementById("app-body"),
    hostInfo: document.getElementById("host-info"),
    studySelect: document.getElementById("study-select"),
    taskRow: document.getElementById("task-row"),
    taskSelect: document.getElementById("task-select"),
    selectModeRow: document.getElementById("select-mode-row"),
    selectMode: document.getElementById("select-mode"),
    sectionSelectionRow: document.getElementById("section-selection-row"),
    sectionCheckboxList: document.getElementById("section-checkbox-list"),
    btnAutoSelect: document.getElementById("btn-auto-select"),
    btnInsertTemplate: document.getElementById("btn-insert-template"),
    drugComparisonRow: document.getElementById("drug-comparison-row"),
    drug1Input: document.getElementById("drug-1-input"),
    drug2Input: document.getElementById("drug-2-input"),
    btnExtractDrugComparison: document.getElementById("btn-extract-drug-comparison"),
    btnSaveDrugComparison: document.getElementById("btn-save-drug-comparison"),
    sectionRow: document.getElementById("section-row"),
    sectionSelect: document.getElementById("section-select"),
    aiRow: document.getElementById("ai-row"),
    btnAi: document.getElementById("btn-ai"),
    openEditorRow: document.getElementById("open-editor-row"),
    btnOpenEditor: document.getElementById("btn-open-editor"),
    finishRow: document.getElementById("finish-row"),
    btnFinishSap: document.getElementById("btn-finish-sap"),
    editorRow: document.getElementById("editor-row"),
    editor: document.getElementById("section-editor"),
    titlePageRow: document.getElementById("titlepage-row"),
    titlePageRoot: document.getElementById("titlepage-editor-root"),
    actionRow: document.getElementById("action-row"),
    btnInsert: document.getElementById("btn-insert"),
    btnClear: document.getElementById("btn-clear"),
    status: document.getElementById("status"),
    saveRow: document.getElementById("save-row"),
    btnSaveDb: document.getElementById("btn-save-db"),
    restoreModal: document.getElementById("restore-modal"),
    btnRestoreYes: document.getElementById("btn-restore-yes"),
    btnRestoreNo: document.getElementById("btn-restore-no"),
    restoreDate: document.getElementById("restore-date"),
    restoreProgressModal: document.getElementById("restore-progress-modal"),
    restoreProgressText: document.getElementById("restore-progress-text")
  };
}

export { getDom };
