const { execFile } = require("child_process");
const crypto = require("crypto");
const fs = require("fs/promises");
const http = require("http");
const https = require("https");
const os = require("os");
const path = require("path");

function escapeRString(value) {
  return String(value || "").replace(/\\/g, "/").replace(/"/g, '\\"');
}

async function fileExists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch (e) {
    return false;
  }
}

async function safeUnlink(filePath) {
  try {
    if (filePath && (await fileExists(filePath))) {
      await fs.unlink(filePath);
    }
  } catch (e) {}
}

function execFileAsync(command, args, options) {
  return new Promise((resolve, reject) => {
    execFile(command, args, options, (error, stdout, stderr) => {
      if (error) {
        error.stdout = stdout;
        error.stderr = stderr;
        reject(error);
        return;
      }
      resolve({ stdout, stderr });
    });
  });
}

function postJson(url, payload, timeoutMs) {
  return new Promise((resolve, reject) => {
    const parsedUrl = new URL(url);
    const body = JSON.stringify(payload || {});
    const client = parsedUrl.protocol === "http:" ? http : https;
    const req = client.request(
      parsedUrl,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Content-Length": Buffer.byteLength(body)
        },
        timeout: timeoutMs
      },
      (res) => {
        let raw = "";
        res.setEncoding("utf8");
        res.on("data", (chunk) => {
          raw += chunk;
        });
        res.on("end", () => {
          let data = null;
          try {
            data = raw ? JSON.parse(raw) : null;
          } catch (e) {
            reject(new Error(`Remote R runner returned non-JSON response: ${raw.slice(0, 160)}`));
            return;
          }
          if (res.statusCode < 200 || res.statusCode >= 300) {
            const message = data?.message || `Remote R runner failed with HTTP ${res.statusCode}`;
            reject(new Error(`${message} (url=${url})`));
            return;
          }
          resolve(data);
        });
      }
    );
    req.on("timeout", () => {
      req.destroy(new Error("Remote R runner request timed out"));
    });
    req.on("error", reject);
    req.write(body);
    req.end();
  });
}

function buildWrappedRCode({ rCodeText, outputPath }) {
  const imagePath = escapeRString(outputPath);
  return [
    "# Auto-generated by the MockTFL Figure workflow.",
    "# The user R code below is executed inside a PNG graphics device.",
    `png(filename = "${imagePath}", width = 1200, height = 800, res = 150)`,
    "tryCatch({",
    String(rCodeText || ""),
    "}, error = function(e) {",
    "  if (dev.cur() > 1) dev.off()",
    "  stop(e)",
    "})",
    "if (dev.cur() > 1) dev.off()"
  ].join("\n");
}

async function generateMockTflFigureFromRCode({ rCodeText }) {
  const code = String(rCodeText || "");
  if (!code.trim()) throw new Error("Missing R code");
  const runnerMode = String(process.env.MOCKTFL_FIGURE_RUNNER || "").trim().toLowerCase();
  const remoteRunnerUrl = String(process.env.MOCKTFL_REMOTE_R_RUNNER_URL || "").trim();
  if (runnerMode === "remote" || remoteRunnerUrl) {
    return await generateMockTflFigureFromRemoteRCode({
      rCodeText: code,
      remoteRunnerUrl
    });
  }

  const id = `${Date.now()}-${crypto.randomBytes(6).toString("hex")}`;
  const tempDir = os.tmpdir();
  const scriptPath = path.join(tempDir, `mocktfl-figure-${id}.R`);
  const imagePath = path.join(tempDir, `mocktfl-figure-${id}.png`);
  const timeoutMs = Number(process.env.MOCKTFL_R_TIMEOUT_MS || 60000);
  // Allow Windows installs that do not expose Rscript on PATH.
  const rscriptPath = process.env.RSCRIPT_PATH || process.env.R_SCRIPT_PATH || "Rscript";

  try {
    await fs.writeFile(scriptPath, buildWrappedRCode({ rCodeText: code, outputPath: imagePath }), "utf8");

    const { stdout, stderr } = await execFileAsync(rscriptPath, ["--vanilla", scriptPath], {
      timeout: Number.isFinite(timeoutMs) ? timeoutMs : 60000,
      windowsHide: true,
      maxBuffer: 1024 * 1024 * 5
    });

    const imageBuffer = await fs.readFile(imagePath);
    if (!imageBuffer.length) {
      throw new Error("Rscript completed, but the generated PNG file is empty.");
    }

    return {
      imageBase64: imageBuffer.toString("base64"),
      mimeType: "image/png",
      stdout: String(stdout || ""),
      stderr: String(stderr || "")
    };
  } catch (err) {
    const stderr = String(err?.stderr || "").trim();
    const detail = stderr || err?.message || String(err);
    throw new Error(`R figure generation failed: ${detail}`);
  } finally {
    await safeUnlink(scriptPath);
    await safeUnlink(imagePath);
  }
}

async function generateMockTflFigureFromRemoteRCode({ rCodeText, remoteRunnerUrl }) {
  const url = String(remoteRunnerUrl || "").trim();
  if (!url) {
    throw new Error("Missing MOCKTFL_REMOTE_R_RUNNER_URL for remote figure generation.");
  }
  const timeoutMs = Number(process.env.MOCKTFL_REMOTE_R_TIMEOUT_MS || process.env.MOCKTFL_R_TIMEOUT_MS || 90000);
  try {
    const data = await postJson(
      url,
      {
        rCodeText: String(rCodeText || "")
      },
      Number.isFinite(timeoutMs) ? timeoutMs : 90000
    );
    const imageBase64 = String(data?.imageBase64 || "").trim();
    if (!imageBase64) {
      throw new Error("Remote R runner did not return imageBase64.");
    }
    return {
      imageBase64,
      mimeType: String(data?.mimeType || "image/png"),
      stdout: String(data?.stdout || ""),
      stderr: String(data?.stderr || "")
    };
  } catch (err) {
    throw new Error(`Remote R figure generation failed: ${err?.message || String(err)}`);
  }
}

module.exports = {
  generateMockTflFigureFromRCode
};
